---
postgres_rhel7_repo: "https://download.postgresql.org/pub/repos/yum/10/redhat/rhel-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm"
postgres_packages:
  - postgresql10 
  - postgresql10-server 
  - postgresql10-contrib 
  - postgresql10-libs
postgres_library: python-psycopg2
postgres_10_data_dir: /var/lib/pgsql/10/data
postgres_10_bin_path: /usr/pgsql-10/bin
postgres_service: postgresql-10.service
postgres_port: 5432
postgres_user: postgres
